 DROP TABLE IF EXISTS cars CASCADE;
 DROP TABLE IF EXISTS clients CASCADE;
 DROP TABLE IF EXISTS experience CASCADE;
 DROP TABLE IF EXISTS mechanic_specialties CASCADE;
 DROP TABLE IF EXISTS mechanics CASCADE;
 DROP TABLE IF EXISTS roles CASCADE;
 DROP TABLE IF EXISTS specialties CASCADE;
 DROP TABLE IF EXISTS types CASCADE;
 DROP TABLE IF EXISTS user_roles CASCADE;
 DROP TABLE IF EXISTS users CASCADE;
 DROP TABLE IF EXISTS visits CASCADE;
 
 CREATE TABLE cars (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 date_of_production DATE, 
 model VARCHAR(20), 
 type_id BIGINT,
 owner_id BIGINT,
 PRIMARY KEY (id));
 
 CREATE TABLE clients (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 address VARCHAR(50), 
 city VARCHAR(20), 
 first_name VARCHAR(50), 
 last_name VARCHAR(50), 
 telephone VARCHAR(10), 
 PRIMARY KEY (id));
 
 CREATE TABLE experience (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 position VARCHAR(30), 
 time_interval VARCHAR(15), 
 mechanic_id BIGINT, 
 PRIMARY KEY (id));
 
 CREATE TABLE mechanic_specialties (
 mechanic_id BIGINT NOT NULL, 
 specialty_id BIGINT NOT NULL, 
 PRIMARY KEY (mechanic_id, specialty_id));
 
 CREATE TABLE mechanics (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 address VARCHAR(50), 
 city VARCHAR(20), 
 first_name VARCHAR(50), 
 last_name VARCHAR(50), 
 telephone VARCHAR(10), 
 PRIMARY KEY (id));
 
 CREATE TABLE roles (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 role VARCHAR(15), 
 PRIMARY KEY (id));
 
 CREATE TABLE specialties (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 name VARCHAR(30), 
 PRIMARY KEY (id));
 
 CREATE TABLE types (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 name VARCHAR(20), 
 PRIMARY KEY (id));
 
 CREATE TABLE user_roles (
 user_id BIGINT NOT NULL, 
 role_id BIGINT NOT NULL, 
 PRIMARY KEY (user_id, role_id));
 
 CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 first_name VARCHAR(30), 
 last_name VARCHAR(30), 
 password VARCHAR(255), 
 user_name VARCHAR(15), 
 PRIMARY KEY (id));
 
 CREATE TABLE visits (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
 visit_date DATE, 
 description VARCHAR(30), 
 car_id BIGINT, 
 mechanic_id BIGINT, 
 PRIMARY KEY (id));
 
 ALTER TABLE users ADD CONSTRAINT UK_k8d0f2n7n88w1a16yhua64onx UNIQUE (user_name);
 ALTER TABLE cars ADD CONSTRAINT FKkd7vilp6m311f5xx2yqhf8o18 FOREIGN KEY (type_id) REFERENCES types;
 ALTER TABLE cars ADD CONSTRAINT FKkfvs5fc35a25mfr65m9bh7lu FOREIGN KEY (owner_id) REFERENCES clients;
 ALTER TABLE experience ADD CONSTRAINT FK798xt68sj2njcjtvq05anf7aj FOREIGN KEY (mechanic_id) REFERENCES mechanics;
 ALTER TABLE mechanic_specialties ADD CONSTRAINT FKkxaomqaogkv0h76q2o1cns7us FOREIGN KEY (specialty_id) REFERENCES specialties;
 ALTER TABLE mechanic_specialties ADD CONSTRAINT FKguaroidn59pvv9o237tws4ond FOREIGN KEY (mechanic_id) REFERENCES mechanics;
 ALTER TABLE user_roles ADD CONSTRAINT FKh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES roles;
 ALTER TABLE user_roles ADD CONSTRAINT FKhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users;
 ALTER TABLE visits ADD CONSTRAINT FKl6w9130b98175p7mx7nlq1mjh FOREIGN KEY (car_id) REFERENCES cars;
 ALTER TABLE visits ADD CONSTRAINT FKsli7sevv6et2g02matn187341 FOREIGN KEY (mechanic_id) REFERENCES mechanics;